import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Navigation } from '@/components/Navigation';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gray-50 dark:bg-gray-900 relative">
          <div className="container mx-auto px-4 py-8">
            <Navigation />
            <main>{children}</main>
          </div>
          <div className="absolute bottom-4 right-4 flex items-center gap-2 divide-x-2">
            <a
              className="text-neutral-900 text-lg font-bold px-2"
              href="https://nextjs.org/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Next16 바로가기
            </a>
            <a
              className="text-neutral-900 text-lg font-bold"
              href="https://github.com/yeonjulee1005/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Dewdew Github
            </a>
          </div>
        </div>
      </body>
    </html>
  );
}
